version: '3.1'

services:
  timereports:
    image: timereports:latest
    build:
      context: .
    command:
      - /usr/src/app/run.sh
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: repo
      PGPASSWORD: postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: repo

